### ISSUE TITLE
Messages in threads appear in reverse order (Element)

### ISSUE THREAD

**Issue by GearKite** [girlbossceo/conduwuit#504] opened 2024-07-03 21:20 UTC
### Steps to reproduce

1. Create a thread, send some messages
2. Restart client to sync again
3. Open thread
4. See messages in reverse order

https://github.com/element-hq/element-web/assets/29222413/d26931a3-3640-4c62-b107-e652191b64bc

(see element-hq/element-web#27664)

**Comment by isosphere** [comment] 2024-07-07 13:50
I'm flailing around with this problem @ https://github.com/isosphere/conduwuit/tree/504_sort_threads

my operating understanding:
- `PduEvent.origin_server_ts` should hypothetically be useful for sorting chronologically
- that field is set by the server on receipt

I have an untested worry that there is a discrepancy between client sent time + order and server recieve time + order. As far as I've been able to understand, the server won't be able to tell if that happened.

**Comment by isosphere** [comment] 2024-07-16 23:21
Here's a capture between element and synapse.

```json
 "timeline": {
    "events": [
        {
            "type": "m.room.message",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "1",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171805468,
            "unsigned": {
                "age": 23055
            },
            "event_id": "$2OA5pqKmifrtyEmjbc_6tbJDm6rmsCCTXJ12egorYDA"
        },
        {
            "type": "m.room.message",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "2",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$2OA5pqKmifrtyEmjbc_6tbJDm6rmsCCTXJ12egorYDA"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171806444,
            "unsigned": {
                "age": 22079
            },
            "event_id": "$T1DcOiCSWiLZbhNynC42gIFnANNg3Rz4hgNuuLXcU7M"
        },
        {
            "type": "m.room.message",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "3",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$T1DcOiCSWiLZbhNynC42gIFnANNg3Rz4hgNuuLXcU7M"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171807659,
            "unsigned": {
                "age": 20864
            },
            "event_id": "$U59vv0DEWtbSi8aTejoZ8JJwb6CFY-1Xi2IjBdSIQ0Q"
        },
        {
            "type": "m.room.message",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "4",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$U59vv0DEWtbSi8aTejoZ8JJwb6CFY-1Xi2IjBdSIQ0Q"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171808453,
            "unsigned": {
                "age": 20070
            },
            "event_id": "$R4AYXbSH9VnH5b0j8uBziJ8zO3R2riPMbPKBvdmWIlE"
        }
    ],
    "prev_batch": "s28_934_2_15_14_1_1_10_0_1",
    "limited": false
}
```

**Comment by isosphere** [comment] 2024-07-17 00:01
This is a synposis including details talked about in the conduwuit matrix group.

The only difference that looks significant to me between Synapse and Conduwuit is that Synapse's unsigned age parameter varies in descending order from oldest to newest messsage, and Conduwuit's value is always 1. 

Here's where age was hardcoded to 1: https://github.com/timokoesters/conduit/commit/acfe381dd3064512272f8f47ea4dd388c04f1c39

Here's what the spec says about it: https://spec.matrix.org/v1.11/client-server-api/#room-event-format
> The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.

**Comment by isosphere** [comment] 2024-08-11 18:16
> The issue most likely lies in underlying event relations code, specifically this line that seems to ignore the direction: https://github.com/girlbossceo/conduwuit/blob/main/src%2Fservice%2Frooms%2Fpdu_metadata%2Fmod.rs#L100

I set a breakpoint at that line and it does not get tripped by a new user joining a test room and clicking an existing thread, nor when starting a new thread and adding to it. I checked my environment by setting a breakpoint on the "typing" service and that tripped.

**Comment by girlbossceo** [comment] 2024-08-12 14:40
Can you compare the direction behaviour request responses between Synapse and conduwuit?

**Comment by isosphere** [comment] 2024-08-12 15:44
> Can you compare the direction behaviour request responses between Synapse and conduwuit?

Clients: 2x `element-desktop` executed via `flatpak` with different profiles. Both clients connected to the same server.

# Synapse

GET `https://s.dataheck.com/_matrix/client/v1/rooms/!fpdVzFVTBbeJtYJCUS%3As.dataheck.com/relations/%24MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY?dir=b`

```
{
    "chunk": [
        {
            "type": "m.room.message",
            "room_id": "!fpdVzFVTBbeJtYJCUS:s.dataheck.com",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "4",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$U59vv0DEWtbSi8aTejoZ8JJwb6CFY-1Xi2IjBdSIQ0Q"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171808453,
            "unsigned": {
                "age": 2304609955
            },
            "event_id": "$R4AYXbSH9VnH5b0j8uBziJ8zO3R2riPMbPKBvdmWIlE",
            "user_id": "@matt:s.dataheck.com",
            "age": 2304609955
        },
        {
            "type": "m.room.message",
            "room_id": "!fpdVzFVTBbeJtYJCUS:s.dataheck.com",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "3",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$T1DcOiCSWiLZbhNynC42gIFnANNg3Rz4hgNuuLXcU7M"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171807659,
            "unsigned": {
                "age": 2304610749
            },
            "event_id": "$U59vv0DEWtbSi8aTejoZ8JJwb6CFY-1Xi2IjBdSIQ0Q",
            "user_id": "@matt:s.dataheck.com",
            "age": 2304610749
        },
        {
            "type": "m.room.message",
            "room_id": "!fpdVzFVTBbeJtYJCUS:s.dataheck.com",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "2",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$2OA5pqKmifrtyEmjbc_6tbJDm6rmsCCTXJ12egorYDA"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171806444,
            "unsigned": {
                "age": 2304611964
            },
            "event_id": "$T1DcOiCSWiLZbhNynC42gIFnANNg3Rz4hgNuuLXcU7M",
            "user_id": "@matt:s.dataheck.com",
            "age": 2304611964
        },
        {
            "type": "m.room.message",
            "room_id": "!fpdVzFVTBbeJtYJCUS:s.dataheck.com",
            "sender": "@matt:s.dataheck.com",
            "content": {
                "msgtype": "m.text",
                "body": "1",
                "m.relates_to": {
                    "rel_type": "m.thread",
                    "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY",
                    "m.in_reply_to": {
                        "event_id": "$MmkcrQpY6rGhBZY4JSNk-Oej0t9itZd01VBYmHSZlJY"
                    },
                    "is_falling_back": true
                }
            },
            "origin_server_ts": 1721171805468,
            "unsigned": {
                "age": 2304612940
            },
            "event_id": "$2OA5pqKmifrtyEmjbc_6tbJDm6rmsCCTXJ12egorYDA",
            "user_id": "@matt:s.dataheck.com",
            "age": 2304612940
        }
    ]
}
```

It requested reverse chronological order, and that's what it got. Shows fine in `element-desktop`: chronological. I visually inspected 3 other similar requests for different threads, they match this behaviour.

# Conduwuit

(I removed my `dir` overriding test for this)


GET `http://sharedbudgets.local/_matrix/client/v1/rooms/!fhpvWsfeOxpE5JKZCB%3Asharedbudgets.local/relations/%24xdd718Rv2y456IfBRnGN_hjlqgkrcI0QpWJ0dL7zLdU?dir=b` [^1]

[^1]: sharedbudgets.local = 127.0.0.1

```
{
    "chunk": [
        {
            "content": {
                "body": "1",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$xdd718Rv2y456IfBRnGN_hjlqgkrcI0QpWJ0dL7zLdU",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$xdd718Rv2y456IfBRnGN_hjlqgkrcI0QpWJ0dL7zLdU"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$jA2D_6tXtlhFQi7EYBUZctS-I6CdJBInBtvZ4EuMZNE",
            "origin_server_ts": 1723477259838,
            "room_id": "!fhpvWsfeOxpE5JKZCB:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {}
        },
        {
            "content": {
                "body": "2",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$xdd718Rv2y456IfBRnGN_hjlqgkrcI0QpWJ0dL7zLdU",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$jA2D_6tXtlhFQi7EYBUZctS-I6CdJBInBtvZ4EuMZNE"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$60IAks924vMegDh8RCsBL4sJc2o0F6U_n3XBBWlNlYA",
            "origin_server_ts": 1723477260171,
            "room_id": "!fhpvWsfeOxpE5JKZCB:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {}
        },
        {
            "content": {
                "body": "3",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$xdd718Rv2y456IfBRnGN_hjlqgkrcI0QpWJ0dL7zLdU",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$60IAks924vMegDh8RCsBL4sJc2o0F6U_n3XBBWlNlYA"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$CS1UCmIZ_Lvo-sZIQRdLngS0c7zC94I3ZiknAU2WafM",
            "origin_server_ts": 1723477260496,
            "room_id": "!fhpvWsfeOxpE5JKZCB:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {}
        },
        {
            "content": {
                "body": "4",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$xdd718Rv2y456IfBRnGN_hjlqgkrcI0QpWJ0dL7zLdU",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$CS1UCmIZ_Lvo-sZIQRdLngS0c7zC94I3ZiknAU2WafM"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$LP83ESqrzGuXVNExrt3fpVDJgqrBHVXXoogKt75GGlQ",
            "origin_server_ts": 1723477260820,
            "room_id": "!fhpvWsfeOxpE5JKZCB:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {}
        },
        {
            "content": {
                "body": "5",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$xdd718Rv2y456IfBRnGN_hjlqgkrcI0QpWJ0dL7zLdU",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$LP83ESqrzGuXVNExrt3fpVDJgqrBHVXXoogKt75GGlQ"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$DPWJ4TDT5XTrGvfKSHfpVZB9Er281O5bvGsKfIB06x8",
            "origin_server_ts": 1723477261258,
            "room_id": "!fhpvWsfeOxpE5JKZCB:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {}
        }
    ],
    "next_batch": "1337",
    "prev_batch": "18446744073709551615"
}
```

Okay, maybe `conduwuit` is wrong. `paginate_relations_with_filter` sees that the client requested `dir`=`Direction::Backward` but we're actually returning data chronologically.

**Comment by isosphere** [comment] 2024-08-16 13:31
Here's a response snippet from the commit referenced above; it's now in reverse order as requested by element:

```json
{
    "chunk": [
        {
            "content": {
                "body": "3",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$7jry-CavwdYk3DEWIgzPEJ8ml9c9HvA7hhqkuV2oxKg",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$42gs7TDdW5voOQFpNgRfiJWzB6gYK83dk-mMRruzXSM"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$TIX0EEGSi-Fsfyrwfx1F8JipvwAzZ8jOjHZ83zggXq8",
            "origin_server_ts": 1723814631141,
            "room_id": "!AX4HOUVizHqi0FSSTZ:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {
                "transaction_id": "m1723814631088.3"
            }
        },
        {
            "content": {
                "body": "2",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$7jry-CavwdYk3DEWIgzPEJ8ml9c9HvA7hhqkuV2oxKg",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$_M8VQjBJm3ivFBQnHwfmXWOtE1JA7fXnlIl0CC5VZdE"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$42gs7TDdW5voOQFpNgRfiJWzB6gYK83dk-mMRruzXSM",
            "origin_server_ts": 1723814630847,
            "room_id": "!AX4HOUVizHqi0FSSTZ:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {
                "transaction_id": "m1723814630790.2"
            }
        },
        {
            "content": {
                "body": "1",
                "m.mentions": {},
                "m.relates_to": {
                    "event_id": "$7jry-CavwdYk3DEWIgzPEJ8ml9c9HvA7hhqkuV2oxKg",
                    "is_falling_back": true,
                    "m.in_reply_to": {
                        "event_id": "$7jry-CavwdYk3DEWIgzPEJ8ml9c9HvA7hhqkuV2oxKg"
                    },
                    "rel_type": "m.thread"
                },
                "msgtype": "m.text"
            },
            "event_id": "$_M8VQjBJm3ivFBQnHwfmXWOtE1JA7fXnlIl0CC5VZdE",
            "origin_server_ts": 1723814630419,
            "room_id": "!AX4HOUVizHqi0FSSTZ:sharedbudgets.local",
            "sender": "@matt:sharedbudgets.local",
            "type": "m.room.message",
            "unsigned": {
                "transaction_id": "m1723814630381.1"
            }
        }
    ],
    "next_batch": "1675",
    "prev_batch": "1682"
}
```
```

**Comment by girlbossceo** [comment] 2024-08-17 05:46
This should be fixed now with https://github.com/girlbossceo/conduwuit/pull/555

**Closed by girlbossceo** 2024-08-17 05:46 UTC
Labels: bug

**Comment by tcpipuk** [comment] 2024-08-17 09:52
Confirmed the latest `main` branch works for me! Thank you both! ❤️
